### ISSUE TITLE
PG_EXPORTER_INCLUDE_DATABASE doesn't work

### ISSUE THREAD

**Issue by erifet** [Vonng/pg_exporter#16]
When I set PG_EXPORTER_AUTO_DISCOVERY = true
to discover the other databases they must absolutely be in --include_database.
The PG_EXPORTER_INCLUDE_DATABASE parameter is not supported.
why is it necessary to have the list of databases in this parameter?
For example if it is empty then we take all the databases which are not in exclude_database.

**Comment by Vonng** [comment]
Thanks for the feedback.

Fixed by https://github.com/Vonng/pg_exporter/commit/f81e436413911b4a34207077c31198ba3d08e0a2
