### ISSUE TITLE
Error when scraping with 2 databases

### ISSUE THREAD

**Issue by erifet** [Vonng/pg_exporter#17]
Having 2 databases assigned, when I try to extract the metrics I have the following error:
An error has occurred while serving metrics:

11 error (s) occurred:
* collected metric "pg_bgwriter_checkpoints_timed" {counter: <value: 73>} was collected before with the same name and label values
* collected metric "pg_bgwriter_checkpoints_req" {counter: <value: 7>} was collected before with the same name and label values
* collected metric "pg_bgwriter_checkpoint_write_time" {counter: <value: 51>} was collected before with the same name and label values
* collected metric "pg_bgwriter_checkpoint_sync_time" {counter: <value: 17>} was collected before with the same name and label values
* collected metric "pg_bgwriter_buffers_checkpoint" {counter: <value: 84>} was collected before with the same name and label values
* collected metric "pg_bgwriter_buffers_clean" {counter: <value: 0>} was collected before with the same name and label values
* collected metric "pg_bgwriter_buffers_backend" {counter: <value: 48>} was collected before with the same name and label values
* collected metric "pg_bgwriter_maxwritten_clean" {counter: <value: 0>} was collected before with the same name and label values
* collected metric "pg_bgwriter_buffers_backend_fsync" {counter: <value: 0>} was collected before with the same name and label values
* collected metric "pg_bgwriter_buffers_alloc" {counter: <value: 1516>} was collected before with the same name and label values
* collected metric "pg_bgwriter_stats_reset" {counter: <value: 1.621928245e + 09>} was collected before with the same name and label values

**Comment by Vonng** [comment]
This is a known issue about config `330-pg_bgwriter.yaml` missing `cluster` tag.
which means it will be scraped in each database. and result in duplication. fixed by https://github.com/Vonng/pg_exporter/commit/f81e436413911b4a34207077c31198ba3d08e0a2
