### ISSUE TITLE
fail connecting to primary server: fail fetching server version

### ISSUE THREAD

**Issue by perrygeo** [Vonng/pg_exporter#23]
Thanks for the great work on this! I'm running `pg_exporter` and I'm hitting an error on the precheck steps.

```
$ pg_exporter
INFO[0000] retrieve target url  from PG_EXPORTER_URL     source="pg_exporter.go:1938"
INFO[0000] retrieve config path pg_exporter.yaml from PG_EXPORTER_CONFIG  source="pg_exporter.go:2009"
ERRO[0000] fail connecting to primary server: fail fetching server version: driver: bad connection, retrying in 10s  source="pg_exporter.go:1517"
```

This appears to be [where the query in question is made](https://github.com/Vonng/pg_exporter/blob/09d4feac1f7ca9eac20caba58c4e8bc02ce1264f/exporter/server.go#L124-L127), `SHOW server_version_num;`

When I connect directly using psql at the same URI, I'm able to run it without issue.

```
$ psql $PG_EXPORTER_URL
psql (12.8 (Ubuntu 12.8-0ubuntu0.20.04.1), server 14.0 (Debian 14.0-1.pgdg110+1))
WARNING: psql major version 12, server major version 14.
         Some psql features might not work.
Type "help" for help.

postgres=# show server_version_num;
 server_version_num 
--------------------
 140000
(1 row)
``` 
I'm not sure how/if it matters but I'm accessing this db over a TCP proxy using `kubectl proxy`. It doesn't seem to impact any other postgres clients but worth mentioning. 

What am I missing?

**Comment by Vonng** [comment]
There's another possibility: Timeout

The start-up - fetch version process has a hard-coded 100ms timeout.

If your RT between postgres & exporter is more than 100ms, which may leads to timeout.

This parameter will becomes to a config entry in next release.

**Comment by Vonng** [comment]
resolved by https://github.com/Vonng/pg_exporter/commit/9b8253b844764cad4f6530ee4933d4209e0eeec1
