### ISSUE TITLE
TLS/SSL support

### ISSUE THREAD

**Issue by keithf4** [Vonng/pg_exporter#24]
Are there any plans for the exporter output to have TLS/SSL support? Just looking through docs and didn't see it mentioned.

**Comment by keithf4** [comment]
Looking at node_exporter (and also a recent commit of postgres_exporter), it looks like they use this toolkit to add in support for TLS and web auth

https://github.com/prometheus/exporter-toolkit

**Comment by Vonng** [comment]
Thanks for your feedback.

It is a reasonable feature (though I didn't use that in production...)

I'll try adding some sort of basic ssl support in next minor release.


> Looking at node_exporter (and also a recent commit of postgres_exporter), it looks like they use this toolkit to add in support for TLS and web auth
> 
> https://github.com/prometheus/exporter-toolkit
> 
> https://github.com/prometheus/exporter-toolkit/tree/master/web

**Comment by Vonng** [comment]
Now using the new prometheus client_golang & exporter-kit library to support TLS. released on 0.6.0
