### ISSUE TITLE
Multple Database implemntation 

### ISSUE THREAD

**Issue by praneeth1133** [Vonng/pg_exporter#3]
Hi,
I'm new to Pg Export.
I'm trying to understand if this implementation supports multiple Postgresql Db.

Thanks,

**Comment by Vonng** [comment]
Currently not..., will be added sometimes later.. 😂

**Comment by praneeth1133** [comment]
Thank you.

**Comment by erifet** [comment]
Hi,

Do you have a schedule for this feature?

Thanks

**Comment by Vonng** [comment]
> Hi,
> 
> Do you have a schedule for this feature?
> 
> Thanks

The rough plan was have a v0.4 release for this before 2021/06/01

**Comment by erifet** [comment]
Thank you for adding it for the next release

**Comment by erifet** [comment]
Hello, is the date of 1 june  for realease 0.4 still valid?
Is it possible to help you, if so how?

**Comment by Vonng** [comment]
> Hello, is the date of 1 june for realease 0.4 still valid?
> Is it possible to help you, if so how?

Deadline is coming..., I'm working on it now. 😆

**Comment by Vonng** [comment]
Implemented by https://github.com/Vonng/pg_exporter/commit/cdce3bf73b1976391cff5fb8c044274f6eefcb24
Further production test needed.

**Comment by Vonng** [comment]
> Hello, is the date of 1 june for realease 0.4 still valid?
> Is it possible to help you, if so how?

I've published a [v0.4.0beta](https://github.com/Vonng/pg_exporter/releases/tag/v0.4.0beta) release. Which could 
 need further test. I would appreciate If you could test v0.4.0beta and give some feedback.

**Comment by erifet** [comment]
I test it tomorrow, thank you

**Comment by erifet** [comment]
Thanks,

With last update PG or PGBOUNCER works well now.

regards,

**Comment by Vonng** [comment]
Add Multiple Database Monitoring Support on v0.4.0
