### ISSUE TITLE
PG 15 beta metrics

### ISSUE THREAD

**Issue by Vonng** [Vonng/pg_exporter#30]
https://www.postgresql.org/docs/15/release-15.html

Some new features about monitoring

* new system view [`pg_stat_subscription_stats`](https://www.postgresql.org/docs/15/monitoring-stats.html#MONITORING-PG-STAT-SUBSCRIPTION_STATS)
* `pg_ls_logicalsnapdir()`, `pg_ls_logicalmapdir()`, and `pg_ls_replslotdir()`.

**Comment by mjf** [comment]
This is very nice resource for comparison between major versions: [PgStats](https://pgstats.dev/).
