### ISSUE TITLE
Just clarify

### ISSUE THREAD

**Issue by localsnet** [Vonng/pg_exporter#5]
Please in 2 words, what is the main difference between this and the https://github.com/wrouesnel/postgres_exporter ?

**Comment by Vonng** [comment]
support [pigsty](https://github.com/Vonng/pigsty)

**Comment by EamonZhang** [comment]
more passionate

**Comment by Vonng** [comment]
To be more specific, some additional features to solve our own problems

* health check (liveness, readyness, primary/replica check interface)
* cache & ttl to reduce multiple prometheus scrape overhead
* version control (same conf for complex environment, e.g from 9.6~13)
* dynamic planning (schedule colloectors basead on tags, taint, condition, schema, extensions)
