### ISSUE TITLE
Increase Caller Skip Depth by One Layer

### ISSUE THREAD

**Issue by ulysseskk** [Vonng/pg_exporter#55]
![image](https://github.com/Vonng/pg_exporter/assets/93476484/17e075a6-5e7f-4df0-b178-177cd6b6644e)
Using the current caller depth skip function only outputs the tool method layer, making it impossible to pinpoint the actual problematic code. The reason is that the logging library by default skips the first 3 layers of calls, but in reality, reaching the actual call requires skipping 4 layers. To solve this problem, it is necessary to specify an additional caller skip layer when initializing the logger.
Current code(utils.go:44):
`
	logger = level.NewFilter(logger, lvl)
	logger = log.With(logger, "timestamp", log.DefaultTimestampUTC, "caller", log.DefaultCaller)
`
Correct code:
`	logger = level.NewFilter(logger, lvl)
	logger = log.With(logger, "timestamp", log.DefaultTimestampUTC, "caller", log.Caller(4))`

**Comment by Vonng** [comment]
Great point! Thank you very much~
Resolved by https://github.com/Vonng/pg_exporter/commit/e41aaff92dae7f704ba951a48387cbcdaf04a304
